// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolHallBooking.Data;

#nullable disable

namespace SchoolHallBooking.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20250915164106_ConvertToOmanTimezone")]
    partial class ConvertToOmanTimezone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SchoolHallBooking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HallId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "BookingDate", "Period")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SchoolHallBooking.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 30,
                            Location = "الطابق الأول",
                            Name = "قاعة التوجيه المهني"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50,
                            Location = "الطابق الأول",
                            Name = "قاعة الفضل"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 200,
                            Location = "الطابق الأرضي",
                            Name = "مركز مصادر التعلم"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 500,
                            Location = "الطابق الثاني",
                            Name = "قاعة اللغة الإنجليزية"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 20,
                            Location = "الطابق الأرضي",
                            Name = "قاعة اللغة العربية"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 40,
                            Location = "الطابق الثاني",
                            Name = "قاعة المهارات الموسيقية"
                        });
                });

            modelBuilder.Entity("SchoolHallBooking.Models.Booking", b =>
                {
                    b.HasOne("SchoolHallBooking.Models.Hall", "Hall")
                        .WithMany("Bookings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("SchoolHallBooking.Models.Hall", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
