version: '3.8'

services:
  school-hall-booking:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    volumes:
      - ./SchoolHallBooking.db:/app/SchoolHallBooking.db
    restart: unless-stopped
