name: school-hall-booking
services:
- name: web
  source_dir: /
  github:
    repo: alazhar98/school-hall-booking
    branch: main
  run_command: dotnet SchoolHallBooking.dll
  environment_slug: dotnet
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    value: Production
  - key: ASPNETCORE_URLS
    value: http://0.0.0.0:8080